
var typewriter = new Typewriter(app, {
    loop: true
});



typewriter.typeString('Bienvenue !')
    .pauseFor(2500)
    .deleteAll()
    .typeString('Je suis William')
    .pauseFor(2500)
    .typeString(', je suis un beau gos')
    .pauseFor(2)
    .deleteChars(8)
    .typeString('étudiant en  Réseau & Télécom à Annecy !')
    .pauseFor(2500)
    .deleteAll()
    .typeString('Je te souhaite la bienvenue sur mon site :)')
    .pauseFor(2500)
    .deleteAll()
    .typeString('Il est actuellement en construction donc tu peux revenir dessus régulièrement')
    .pauseFor(2500)
    .deleteAll()
    .typeString('Tu peux me contacter via les liens en bas')
    .pauseFor(2500)
    .deleteAll()
    .typeString('Amuse toi bien ;)')
    .pauseFor(2000)
    .deleteAll()
    .pauseFor(80000)
    .typeString('Toujours là ?')
    .pauseFor(2000)
    .deleteAll()
    .typeString('Tu es un fan de easter eggs dis donc')
    .pauseFor(2000)
    .deleteAll()
    .typeString('Bon ok tu as gagné, refresh la page dans')
    .pauseFor(200)
    .deleteAll()
    .typeString('3')
    .deleteAll()
    .typeString('2')
    .deleteAll()
    .typeString('1')
    .deleteAll()
    .typeString('Gooo !!!!!')
    .pauseFor(300)
    .deleteAll()
    .typeString('Trop tard, perdu :^)')
    .start();
